{% set name = "tinygp" %}
{% set version = "0.2.4" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/tinygp-{{ version }}.tar.gz
  sha256: 7e88a607a5ec83efadadf229903908e9b195273c5345ef60bdd38a809a3c6504

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - hatchling
    - hatch-vcs
    - pip
    - python >=3.9
  run:
    - jax
    - jaxlib
    - python >=3.9

test:
  imports:
    - tinygp
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/dfm/tinygp
  doc_url: https://tinygp.readthedocs.io/
  summary: The tiniest of Gaussian Process libraries
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - thewchan
