{% set name = "tinygp" %}
{% set version = "0.2.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/tinygp-{{ version }}.tar.gz
  sha256: 15b2426d4ec232b4649286e32dcad7a2680b09e09b0c857dee8eabfa99244e7b

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - python >=3.6
    - setuptools >=40.6.0,<60.9.0
    - setuptools-scm
  run:
    - jax
    - jaxlib
    - python >=3.6

test:
  imports:
    - tinygp
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/dfm/tinygp
  doc_url: https://tinygp.readthedocs.io/
  summary: The tiniest of Gaussian Process libraries
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - thewchan
